apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- training-job-patch.yaml
resources:
- ../../base
images:
- name: ghcr.io/kimjunil/mnist_classifier_katib
  newTag: 0.1.5
