apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: mnist-katib
  name: mnist-katib-experiment
spec:
  metricsCollectorSpec:
    collector:
      kind: StdOut
    source:
      filter:
        metricsFormat:
          - "([\\w|-]+)\\s*=\\s*((-?\\d+)(\\.\\d+)?)"
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - Train-accuracy
      - Train-loss
      - Validation-loss
  algorithm:
    algorithmName: random
  parallelTrialCount: 2
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: units
      parameterType: int
      feasibleSpace:
        min: "64"
        max: "512"

  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: units
        description: units
        reference: units
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: ghcr.io/kimjunil/mnist_classifier_katib:0.1.2
                command:
                  - "python"
                  - "app/train.py"
                  - "--units=${trialParameters.units}"
            restartPolicy: Never

# apiVersion: kubeflow.org/v1beta1
# kind: Experiment
# metadata:
#   namespace: mnist-katib
#   name: simple-mnist
# spec:
#   objective:
#     type: maximize
#     goal: 0.99
#     objectiveMetricName: test-acc
#     additionalMetricNames:
#       - test-loss
#   algorithm:
#     algorithmName: random
#   parallelTrialCount: 2
#   maxTrialCount: 12
#   maxFailedTrialCount: 3
#   parameters:
#     - name: hidden_units
#       parameterType: int
#       feasibleSpace:
#         min: "32"
#         max: "256"
#   trialTemplate:
#     primaryContainerName: training-container
#     trialParameters:
#       - name: hidden_units
#         description: hidden layer unints
#         reference: hidden_units
#     trialSpec:
#       apiVersion: batch/v1
#       kind: Job
#       spec:
#         template:
#           spec:
#             containers:
#               - name: training-container
#                 image: ghcr.io/kimjunil/mnist_classifier_katib:0.0.11
#                 command:
#                   - "python"
#                   - "/train.py"
#                   - "--hidden_units=${trialParameters.hidden_units}"
#             restartPolicy: Never