apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: mnist-katib
  name: mnist-katib-experiment
spec:
  metricsCollectorSpec:
    collector:
      kind: StdOut
    source:
      filter:
        metricsFormat:
          - "([\\w|-]+)\\s*:\\s*((-?\\d+)(\\.\\d+)?)"
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: val_accuracy
    additionalMetricNames:
      - accuracy
  algorithm:
    algorithmName: random
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - feasibleSpace:
        max: "0.03"
        min: "0.01"
      name: lr
      parameterType: double
    - feasibleSpace:
        max: "0.8"
        min: "0.1"
      name: do
      parameterType: double

  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learning_rate
        description: learning rate
        reference: lr
      - name: dropout
        description: dropout
        reference: do
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: ghcr.io/kimjunil/mnist_classifier_katib:0.0.6
                command:
                  - "python"
                  - "app/train.py"
                  - "--dropout=${trialParameters.dropout}"
                  - "--learning_rate=${trialParameters.learning_rate}"
            restartPolicy: Never