apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: mnist-katib
  name: mnist-katib-experiment
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: val_accuracy
    additionalMetricNames:
      - accuracy
  algorithm:
    algorithmName: random
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: hidden_units
      parameterType: int
      feasibleSpace:
        min: "32"
        max: "256"
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learning_rate
        description: learning rate
        reference: learning_rate
      - name: dropout
        description: dropout
        reference: dropout
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: ghcr.io/kimjunil/mnist_classifier_katib:0.0.3
                command:
                  - "python"
                  - "app/train.py"
                  - "--dropout=${trialParameters.dropout}"
                  - "--learning_rate=${trialParameters.learning_rate}"
            restartPolicy: Never